paths-ignore:
  - dist/**
  - node_modules/**
  - pnpm-lock.yaml
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - .env.example

paths:
  - src/**
  - .github/**
  - "*.ts"
  - "*.js"
  - "*.json"
  - "*.yml"
  - "*.yaml"
