apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus-bv
    type: prometheus
    access: proxy
    url: http://bv-prometheus:9090
    isDefault: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s
    editable: false
